#spring.datasource.url= jdbc:mysql://localhost/mydb2
#spring.datasource.driverClassName= com.mysql.cj.jdbc.Driver
#spring.datasource.username= root
#spring.datasource.password= root
#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQL5InnoDBDialect
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb2?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
     hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
     hibernate.ddl-auto: update
     hibernate:
       jdbc: time_zone = TimeZone
